 #Comment définir les sources
 # schema.yml

 version: 2

 sources:
   - name: raw_data
     schema: gz_raw_data
     tables:
       - name: sales
         identifier: gw_raw-sales
       - name: product
         identifier: gw_raw_product
       - name: ship
         identifier: gw_raw_ship